language: go
go:
- 1.11.x
env:
- GO111MODULE=on
install:
- go mod vendor

before_script:
- go vet -x ./...

matrix:
  include:
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: go test -v -race -mod=vendor ./...

